version: '3.9'

services:
  application.webapi:
    image: genocs/demo-webapi:2.0.0
    build:
      context: .
      dockerfile: webapi.dockerfile

  application.worker:
    image: genocs/demo-worker:2.0.0
    build:
      context: .
      dockerfile: worker.dockerfile
