services:
  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    hostname: aspire_dashboard
    container_name: aspire_dashboard
    ports:
      - 18888:18888
      - 4318:18889

    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

    networks:
      - genocs
    # network_mode: host

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - genocs
    # network_mode: host
    volumes:
      - grafana:/var/lib/grafana

  influxdb:
    image: influxdb
    hostname: influxdb
    container_name: influxdb
    ports:
      - 8086:8086
    networks:
      - genocs
    # network_mode: host
    volumes:
      - influxdb:/var/lib/influxdb2

  jaeger:
    image: jaegertracing/all-in-one
    hostname: jaeger_node_1
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
      - 4317:4317
    # network_mode: host
    networks:
      - genocs

  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - genocs
    # network_mode: host
    volumes:
      - prometheus:/etc/prometheus

  seq:
    image: datalust/seq
    hostname: seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - genocs
    # network_mode: host
    volumes:
      - seq:/data

networks:
  genocs:
    name: genocs-network
    external: true

volumes:
  grafana:
    driver: local
  influxdb:
    driver: local
  prometheus:
    driver: local
  seq:
    driver: local
