services:
  mysqldb:
    image: mysql
    hostname: mysqldb
    container_name: mysqldb
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: MySect3tPassw!
    volumes:
      - mysqlsystem:/var/lib/mysql
    networks:
      - genocs

networks:
  genocs:
    name: genocs-network
    external: true

volumes:
  mysqlsystem:
    driver: local
