global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:5000"]
#
# - job_name: 'users-service'
#   static_configs:
#     - targets: ['users-service:5000']
#
# - job_name: 'notifications-service'
#   static_configs:
#     - targets: ['notifications-service:5000']
#
# - job_name: 'operations-service'
#   static_configs:
#     - targets: ['operations-service:5000']
#
# - job_name: 'signalr-service'
#   static_configs:
#     - targets: ['signalr-service:5000']
