apiVersion: v1
kind: Service

metadata:
  name: voucher-service
  namespace: utu-taxfree
  labels:
    run: voucher-webapi

spec:
  type: ClusterIP

  ports:
    - protocol: TCP
      name: http-port
      port: 80
      targetPort: 8080

  selector:
    run: voucher-webapi
