version: '3.9'

services:
  apigateway:
    image: genocs/apigateway:9.0.0
    build:
      context: .
      dockerfile: apigateway.dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  identity.webapi:
    image: genocs/identity-webapi:9.0.0
    build:
      context: .
      dockerfile: identity-webapi.dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

networks:
  genocs:
    name: genocs-network
    external: true
    driver: bridge
