version: '3.9'

services:
  apigateway:
    image: genocs/apigateway:1.0.0
    hostname: apigateway_node_1
    container_name: apigateway
    build:
      context: .
      dockerfile: apigateway.dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5500:80

    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - apigateway:/var/lib/data

  identity.webapi:
    image: genocs/identity-webapi:1.0.0
    hostname: identity_node_1
    container_name: identity
    build:
      context: .
      dockerfile: identity-webapi.dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

    ports:
      - 5510:80

    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - identity:/var/lib/data

  product.webapi:
    image: genocs/product-webapi:1.0.0
    hostname: product_node_1
    container_name: product
    build:
      context: .
      dockerfile: product-webapi.dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

    # External ports not enabled because of the apigateway
    #ports:
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - product:/var/lib/data

  order.webapi:
    image: genocs/order-webapi:1.0.0
    hostname: order_node_1
    container_name: order
    build:
      context: .
      dockerfile: order-webapi.dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

    # External ports not enabled because of the apigateway
    #ports:
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - order:/var/lib/data

  signalr.webapi:
    image: genocs/signalr-webapi:1.0.0
    hostname: signalr_node_1
    container_name: signalr
    build:
      context: .
      dockerfile: signalr-webapi.dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

    # External ports not enabled because of the apigateway
    #ports:
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - signalr:/var/lib/data

networks:
  genocs:
    name: genocs-network
    external: true
    driver: bridge

volumes:
  apigateway:
    driver: local
  identity:
    driver: local
  product:
    driver: local
  order:
    driver: local
  signalr:
    driver: local
