version: '3.9'

services:
  api-gateway:
    build:
      context: .
      dockerfile: apigateway.dockerfile

  identity-service:
    build:
      context: .
      dockerfile: identity-webapi.dockerfile

  products-service:
    build:
      context: .
      dockerfile: product-webapi.dockerfile

  orders-service:
    build:
      context: .
      dockerfile: order-webapi.dockerfile

  signalr-service:
    build:
      context: .
      dockerfile: signalr-webapi.dockerfile
