version: '3.9'

services:
  apigateway:
    image: genocs/apigateway:${IMAGE_VERSION}
    hostname: apigateway
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5500:80
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - apigateway:/var/lib/data

  identity.webapi:
    image: genocs/identity-webapi:${IMAGE_VERSION}
    hostname: identity
    container_name: identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5501:80
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - identity:/var/lib/data

  products.webapi:
    image: genocs/product-webapi:${IMAGE_VERSION}
    hostname: products
    container_name: products
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    # External ports not enabled because of the apigateway
    #ports:
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - products:/var/lib/data

  orders.webapi:
    image: genocs/order-webapi:${IMAGE_VERSION}
    hostname: orders
    container_name: orders
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

    # External ports not enabled because of the apigateway
    #ports:
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - orders:/var/lib/data

  signalr.webapi:
    image: genocs/signalr-webapi:${IMAGE_VERSION}
    hostname: signalr
    container_name: signalr
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    # External ports not enabled because of the apigateway
    #ports:
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - signalr:/var/lib/data
networks:
  genocs:
    name: genocs-network
    external: true
    driver: bridge

volumes:
  apigateway:
    driver: local
  identity:
    driver: local
  products:
    driver: local
  orders:
    driver: local
  signalr:
    driver: local
