services:
  apigateway:
    image: genocs/apigateway:${IMAGE_VERSION}
    hostname: api-gateway
    container_name: api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIROMENT}
      - consul__url=${CONSUL_URL}
      - consul__address=api-gateway
      - consul__port=8080
      - fabio__url=${FABIO_URL}
      - jaeger__udpHost=${JAEGER_URL}
      - openTelemetry__otlpEndpoint=${JAEGER_URL}
      - mongodb__connectionString=mongodb://mongodb:27017
      - reverseProxy__clusters__identity-cluster__destinations__destination1__address=http://identity-service:8080
      - reverseProxy__clusters__products-cluster__destinations__destination1__address=http://products-service:8080
      - reverseProxy__clusters__orders-cluster__destinations__destination1__address=http://orders-service:8080
      - reverseProxy__clusters__notifications-cluster__destinations__destination1__address=http://notifications-service:8080

    ports:
      - 5500:8080
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - apigateway:/root/.aspnet/DataProtection-Keys

  identity-service:
    image: genocs/identity-webapi:${IMAGE_VERSION}
    hostname: identity-service
    container_name: identity-service
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIROMENT}
      - consul__url=${CONSUL_URL}
      - consul__address=identity-service
      - consul__port=8080
      - fabio__url=${FABIO_URL}
      - jaeger__udpHost=${JAEGER_URL}
      - openTelemetry__otlpEndpoint=${JAEGER_URL}
      - mongodb__connectionString=mongodb://mongodb:27017

    ports:
      - 5510:8080
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - identity:/root/.aspnet/DataProtection-Keys

  products-service:
    image: genocs/product-webapi:${IMAGE_VERSION}
    hostname: products-service
    container_name: products-service
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIROMENT}
      - consul__url=${CONSUL_URL}
      - consul__address=products-service
      - consul__port=8080
      - fabio__url=${FABIO_URL}
      - jaeger__udpHost=${JAEGER_URL}
      - openTelemetry__otlpEndpoint=${JAEGER_URL}
      - mongodb__connectionString=mongodb://mongodb:27017

    ports:
      - 5520:8080
    #ports:
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - products:/root/.aspnet/DataProtection-Keys

  orders-service:
    image: genocs/order-webapi:${IMAGE_VERSION}
    hostname: orders-service
    container_name: orders-service
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIROMENT}
      - consul__url=${CONSUL_URL}
      - consul__address=orders-service
      - consul__port=8080
      - fabio__url=${FABIO_URL}
      - jaeger__udpHost=${JAEGER_URL}
      - openTelemetry__otlpEndpoint=${JAEGER_URL}
      - mongodb__connectionString=mongodb://mongodb:27017

    ports:
      - 5530:8080
    #ports:
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - orders:/root/.aspnet/DataProtection-Keys

  notifications-service:
    image: genocs/notifications-webapi:${IMAGE_VERSION}
    hostname: notifications-service
    container_name: notifications-service
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIROMENT}
      - consul__url=${CONSUL_URL}
      - consul__address=notifications-service
      - consul__port=8080
      - fabio__url=${FABIO_URL}
      - jaeger__udpHost=${JAEGER_URL}
      - openTelemetry__otlpEndpoint=${JAEGER_URL}
      - mongodb__connectionString=mongodb://mongodb:27017

    ports:
      - 5540:8080
    #ports:
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - signalr:/root/.aspnet/DataProtection-Keys

networks:
  genocs:
    name: genocs-network
    external: true
    driver: bridge

volumes:
  apigateway:
    driver: local
  identity:
    driver: local
  products:
    driver: local
  orders:
    driver: local
  notifications:
    driver: local
