version: '3.9'

services:
  api-gateway:
    image: genocs/apigateway:${IMAGE_VERSION}
    hostname: api-gateway
    container_name: api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5500:80
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - apigateway:/var/lib/data

  identity-service:
    image: genocs/identity-webapi:${IMAGE_VERSION}
    hostname: identity-service
    container_name: identity-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5501:80
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - identity:/var/lib/data

  products-service:
    image: genocs/product-webapi:${IMAGE_VERSION}
    hostname: products-service
    container_name: products-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5502:80
    #ports:
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - products:/var/lib/data

  orders-service:
    image: genocs/order-webapi:${IMAGE_VERSION}
    hostname: orders-service
    container_name: orders-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5503:80
    #ports:
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - orders:/var/lib/data

  signalr-service:
    image: genocs/signalr-webapi:${IMAGE_VERSION}
    hostname: signalr-service
    container_name: signalr-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5504:80
    #ports:
    networks:
      - genocs
    # network_mode: bridge
    volumes:
      - signalr:/var/lib/data
networks:
  genocs:
    name: genocs-network
    external: true
    driver: bridge

volumes:
  apigateway:
    driver: local
  identity:
    driver: local
  products:
    driver: local
  orders:
    driver: local
  signalr:
    driver: local
