services:
  api-gateway:
    build:
      context: .
      dockerfile: apigateway.dockerfile

  identity-service:
    build:
      context: .
      dockerfile: identity.dockerfile

  products-service:
    build:
      context: .
      dockerfile: products.dockerfile

  orders-service:
    build:
      context: .
      dockerfile: orders.dockerfile

  signalr-service:
    build:
      context: .
      dockerfile: signalr.dockerfile
