name: Publish on NuGet

on:
  push:
    branches:
      - deploy
  pull_request:
    types: [closed]
    branches:
      - deploy

jobs:
  build:
    name: Update NuGet package  
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
          source-url: https://nuget.pkg.github.com/genocs/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
          
      - name: Build solution and generate NuGet package
        run: dotnet pack -c Debug -o out  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./out/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true
