name: Publish on NuGet

on:
  push:
    branches:
      - deploy
  pull_request:
    types: [closed]
    branches:
      - deploy

jobs:
  build:
    name: Update NuGet package  
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v2
        with:
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - name: Build
        run: dotnet build --no-restore
          
      - name: Build solution and generate NuGet package
        run: |  
          dotnet pack -c Debug -o out  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true
